<a href="https://colab.research.google.com/github/maxprogrammer007/PDS-CSVTU-Sem2/blob/main/Basics_Of_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(8)
print(tensor_zero_d)

tf.Tensor(8, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [4]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [5]:
tensor_three_d = tf.constant([

                              [[1,2,3],
                               [3,5,-1]],

                              [[10,3,4],
                               [1,5,6]],

                              [[6,5,3],
                               [45,76,9]],

                              [[2,5,3],
                               [5,4,5]]
])

In [6]:
tensor_four_d = tf.constant([
    [

                              [[1,2,3],
                               [3,5,-1]],

                              [[10,3,4],
                               [1,5,6]],

                              [[6,5,3],
                               [45,76,9]],

                              [[2,5,3],
                               [5,4,5]]
],
     [

                              [[1,2,3],
                               [3,5,-1]],

                              [[10,3,4],
                               [1,5,6]],

                              [[6,5,3],
                               [45,76,9]],

                              [[2,5,3],
                               [5,4,5]]
],
      [

                              [[1,2,3],
                               [3,5,-1]],

                              [[10,3,4],
                               [1,5,6]],

                              [[6,5,3],
                               [45,76,9]],

                              [[2,5,3],
                               [5,4,5]]
]
])

In [7]:
import numpy as np


In [8]:
arr = np.array([1,2,3,4,5,6,7,8,9])
coverted_tensor = tf.convert_to_tensor(arr)

In [9]:
print(coverted_tensor)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


In [10]:
eye_tensor = tf.eye(
    num_rows=4,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

In [11]:
print(eye_tensor)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [12]:
eye_tensor1 = tf.eye(
    num_rows=4,
    num_columns=6,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor1)

tf.Tensor(
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]], shape=(4, 6), dtype=float32)


In [13]:
eye_tensor2 = tf.eye(
    num_rows=4,
    num_columns=None,
    batch_shape=[2],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor2)

tf.Tensor(
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape=(2, 4, 4), dtype=float32)


In [14]:
filled_tensor = tf.fill([2,3], 8)

In [15]:
print(filled_tensor)

tf.Tensor(
[[8 8 8]
 [8 8 8]], shape=(2, 3), dtype=int32)


In [16]:
tf.shape(tensor_four_d)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 2, 3])>

In [17]:
tf.size(tensor_four_d)

<tf.Tensor: shape=(), dtype=int32, numpy=72>

In [20]:
# random tensors

randome_tensor = tf.random.normal(
    [3,2,2],
    mean =0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

In [21]:
print(randome_tensor)

tf.Tensor(
[[[-0.94215214 -0.68370026]
  [ 0.15898167 -0.9476472 ]]

 [[ 0.5433289  -0.74997306]
  [ 0.7603781   0.90746987]]

 [[ 0.47381338 -0.22523715]
  [-0.25446403  0.23084885]]], shape=(3, 2, 2), dtype=float32)


In [22]:
#uniform tensor
uniform_tensor = tf.random.uniform(
    [2,4,5],
    minval = 0,
    maxval = None,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)

In [23]:
print(uniform_tensor)

tf.Tensor(
[[[0.5950475  0.664094   0.8105799  0.7654351  0.0633949 ]
  [0.05833912 0.13866317 0.17369008 0.06138539 0.25493038]
  [0.5600575  0.15159655 0.27926755 0.9447837  0.486354  ]
  [0.10908127 0.7079065  0.0742588  0.9124538  0.348966  ]]

 [[0.07500505 0.50155103 0.8346634  0.42695498 0.9723712 ]
  [0.01290166 0.93380535 0.0856235  0.9937459  0.25540137]
  [0.6791761  0.38062    0.726624   0.80450785 0.3083142 ]
  [0.5216892  0.08864832 0.02486145 0.4966612  0.9902508 ]]], shape=(2, 4, 5), dtype=float32)
