<a href="https://colab.research.google.com/github/maxprogrammer007/PDS-CSVTU-Sem2/blob/main/Basics_Of_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(8)
print(tensor_zero_d)

tf.Tensor(8, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [4]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [5]:
tensor_three_d = tf.constant([

                              [[1,2,3],
                               [3,5,-1]],

                              [[10,3,4],
                               [1,5,6]],

                              [[6,5,3],
                               [45,76,9]],

                              [[2,5,3],
                               [5,4,5]]
])

In [6]:
tensor_four_d = tf.constant([
    [

                              [[1,2,3],
                               [3,5,-1]],

                              [[10,3,4],
                               [1,5,6]],

                              [[6,5,3],
                               [45,76,9]],

                              [[2,5,3],
                               [5,4,5]]
],
     [

                              [[1,2,3],
                               [3,5,-1]],

                              [[10,3,4],
                               [1,5,6]],

                              [[6,5,3],
                               [45,76,9]],

                              [[2,5,3],
                               [5,4,5]]
],
      [

                              [[1,2,3],
                               [3,5,-1]],

                              [[10,3,4],
                               [1,5,6]],

                              [[6,5,3],
                               [45,76,9]],

                              [[2,5,3],
                               [5,4,5]]
]
])

In [7]:
import numpy as np


In [8]:
arr = np.array([1,2,3,4,5,6,7,8,9])
coverted_tensor = tf.convert_to_tensor(arr)

In [9]:
print(coverted_tensor)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


In [10]:
eye_tensor = tf.eye(
    num_rows=4,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

In [11]:
print(eye_tensor)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [12]:
eye_tensor1 = tf.eye(
    num_rows=4,
    num_columns=6,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor1)

tf.Tensor(
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]], shape=(4, 6), dtype=float32)


In [13]:
eye_tensor2 = tf.eye(
    num_rows=4,
    num_columns=None,
    batch_shape=[2],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor2)

tf.Tensor(
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape=(2, 4, 4), dtype=float32)


In [14]:
filled_tensor = tf.fill([2,3], 8)

In [15]:
print(filled_tensor)

tf.Tensor(
[[8 8 8]
 [8 8 8]], shape=(2, 3), dtype=int32)


In [16]:
tf.shape(tensor_four_d)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 2, 3])>

In [17]:
tf.size(tensor_four_d)

<tf.Tensor: shape=(), dtype=int32, numpy=72>