# Numpy Advanced Stuffs

In [1]:
import numpy as np

## Speed comparision of Numpy Array and Python Lists

In [2]:
# Speed 
# List
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time 

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time() - start)

4.278988599777222


In [4]:
# numpy 
a = np.arange(10000000)
b = np.arange(10000000,20000000)
start = time.time()
c = a+b 
print(time.time() - start)

0.01565861701965332


In [5]:
# How many times faster ?
4.278988599777222 / 0.01565861701965332

273.2673386421426

### reason for faster output - numpy arrays use CTYPE Arrays whose sizes are fixed and they do not use referential arrays it means you directly put the data into the memory block and do not put their memory address.

In [6]:
# Fayda in terms of MEMORY
a = [ i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [7]:
a = np.arange(10000000)

sys.getsizeof(a)

40000112

In [8]:
# difference in size of memory blocks
89095160 / 40000112

2.2273727633562626

# Advanced Indexing

In [13]:
# Normal indexing and slicing 

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
a[1,2]

6

In [11]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

## Fancy Indexing and Boolean Indexing



In [16]:
a 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
# now i need to print 1st ,second, third , last row

a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [18]:
a[:,[0,2,3]] # printing all elements of columns 0,2,3

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])