# Numpy Advanced Stuffs

In [1]:
import numpy as np

## Speed comparision of Numpy Array and Python Lists

In [2]:
# Speed 
# List
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time 

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time() - start)

4.278988599777222


In [4]:
# numpy 
a = np.arange(10000000)
b = np.arange(10000000,20000000)
start = time.time()
c = a+b 
print(time.time() - start)

0.01565861701965332


In [5]:
# How many times faster ?
4.278988599777222 / 0.01565861701965332

273.2673386421426

### reason for faster output - numpy arrays use CTYPE Arrays whose sizes are fixed and they do not use referential arrays it means you directly put the data into the memory block and do not put their memory address.

In [6]:
# Fayda in terms of MEMORY
a = [ i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [7]:
a = np.arange(10000000)

sys.getsizeof(a)

40000112

In [8]:
# difference in size of memory blocks
89095160 / 40000112

2.2273727633562626

# Advanced Indexing

In [13]:
# Normal indexing and slicing 

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
a[1,2]

6

In [11]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

## Fancy Indexing and Boolean Indexing



In [16]:
a 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
# now i need to print 1st ,second, third , last row

a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [18]:
a[:,[0,2,3]] # printing all elements of columns 0,2,3

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [20]:
# Boolean Indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[33, 98, 59, 79],
       [41, 78, 60, 34],
       [23, 59, 15, 69],
       [97,  7, 57, 70],
       [52, 80, 66, 33],
       [84, 87, 81, 58]])

In [21]:
# find all numbers greater than 50
a > 50

array([[False,  True,  True,  True],
       [False,  True,  True, False],
       [False,  True, False,  True],
       [ True, False,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True]])

In [22]:
a[a>50] # boolean masking

array([98, 59, 79, 78, 60, 59, 69, 97, 57, 70, 52, 80, 66, 84, 87, 81, 58])

In [23]:
# Find out even numbers
 
a % 2 ==  0

array([[False,  True, False, False],
       [False,  True,  True,  True],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True, False],
       [ True, False, False,  True]])

In [24]:
a[a % 2 ==  0]

array([98, 78, 60, 34, 70, 52, 80, 66, 84, 58])

In [26]:
# Find all numbers greater than 50 and are even
( a > 50 ) & ( a % 2 == 0)

array([[False,  True, False, False],
       [False,  True,  True, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True, False],
       [ True, False, False,  True]])

In [27]:
a[( a > 50 ) & ( a % 2 == 0)]

array([98, 78, 60, 70, 52, 80, 66, 84, 58])

In [28]:
# Find all numbers which are not divisible by zero

a % 7 != 0

array([[ True, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True,  True],
       [False,  True,  True,  True]])

In [29]:
a[a % 7 != 0]

array([33, 59, 79, 41, 78, 60, 34, 23, 59, 15, 69, 97, 57, 52, 80, 66, 33,
       87, 81, 58])

# Broadcasting

> The term broadcasting describes how Numpy treats arrays with different shapes during arithmetic operations.\
The smalller array is " broadcast " across the larger array so that they have compatible shapes

In [30]:
# same shape

a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [31]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


#### Broadcasting Rules

**1. Make the two arrays have the same number of dimensions.**<br>
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

**2. Make each dimension of the two arrays the same size.**<br>
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">