In [1]:
import numpy as np

# np.sort

Return a sorted copy of an array.

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([16, 28, 76, 92, 72, 95, 59, 14, 23, 30, 39, 27, 11, 36, 76])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[23, 30, 65, 65],
       [34, 39, 80, 97],
       [29, 17, 26, 78],
       [34, 12, 59, 99],
       [48, 71,  3, 33],
       [38, 36, 68, 87]])

In [4]:
np.sort(a)[::-1]

array([95, 92, 76, 76, 72, 59, 39, 36, 30, 28, 27, 23, 16, 14, 11])

In [5]:
np.sort(b,axis=0)

array([[23, 12,  3, 33],
       [29, 17, 26, 65],
       [34, 30, 59, 78],
       [34, 36, 65, 87],
       [38, 39, 68, 97],
       [48, 71, 80, 99]])