In [1]:
import numpy as np

# np.sort

Return a sorted copy of an array.\
https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([16, 28, 76, 92, 72, 95, 59, 14, 23, 30, 39, 27, 11, 36, 76])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[23, 30, 65, 65],
       [34, 39, 80, 97],
       [29, 17, 26, 78],
       [34, 12, 59, 99],
       [48, 71,  3, 33],
       [38, 36, 68, 87]])

In [6]:
np.sort(a)

array([11, 14, 16, 23, 27, 28, 30, 36, 39, 59, 72, 76, 76, 92, 95])

In [4]:
np.sort(a)[::-1] # for descending order

array([95, 92, 76, 76, 72, 59, 39, 36, 30, 28, 27, 23, 16, 14, 11])

In [5]:
np.sort(b,axis=0) # for column wise 

array([[23, 12,  3, 33],
       [29, 17, 26, 65],
       [34, 30, 59, 78],
       [34, 36, 65, 87],
       [38, 39, 68, 97],
       [48, 71, 80, 99]])

In [7]:
np.sort(b) #row wise

array([[23, 30, 65, 65],
       [34, 39, 80, 97],
       [17, 26, 29, 78],
       [12, 34, 59, 99],
       [ 3, 33, 48, 71],
       [36, 38, 68, 87]])

# np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [8]:
# code
np.append(a,200)

array([ 16,  28,  76,  92,  72,  95,  59,  14,  23,  30,  39,  27,  11,
        36,  76, 200])

In [9]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[2.30000000e+01, 3.00000000e+01, 6.50000000e+01, 6.50000000e+01,
        5.80998571e-01],
       [3.40000000e+01, 3.90000000e+01, 8.00000000e+01, 9.70000000e+01,
        5.70854409e-01],
       [2.90000000e+01, 1.70000000e+01, 2.60000000e+01, 7.80000000e+01,
        3.73550496e-01],
       [3.40000000e+01, 1.20000000e+01, 5.90000000e+01, 9.90000000e+01,
        1.84389523e-01],
       [4.80000000e+01, 7.10000000e+01, 3.00000000e+00, 3.30000000e+01,
        5.32060437e-01],
       [3.80000000e+01, 3.60000000e+01, 6.80000000e+01, 8.70000000e+01,
        7.14046685e-02]])

In [11]:
np.append(b,np.random.random((b.shape[0],1)))

array([23.        , 30.        , 65.        , 65.        , 34.        ,
       39.        , 80.        , 97.        , 29.        , 17.        ,
       26.        , 78.        , 34.        , 12.        , 59.        ,
       99.        , 48.        , 71.        ,  3.        , 33.        ,
       38.        , 36.        , 68.        , 87.        ,  0.12103136,
        0.18699272,  0.80777865,  0.22888467,  0.39846238,  0.79855876])

In [16]:
np.append(b,np.ones((b.shape[0],1)),axis=1) # adding 1 at last column

array([[23., 30., 65., 65.,  1.],
       [34., 39., 80., 97.,  1.],
       [29., 17., 26., 78.,  1.],
       [34., 12., 59., 99.,  1.],
       [48., 71.,  3., 33.,  1.],
       [38., 36., 68., 87.,  1.]])

# np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [17]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [18]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [20]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [21]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [22]:
# code
a.shape

(15,)

In [23]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [26]:
np.expand_dims(a,axis=1)

array([[16],
       [28],
       [76],
       [92],
       [72],
       [95],
       [59],
       [14],
       [23],
       [30],
       [39],
       [27],
       [11],
       [36],
       [76]])

# np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [27]:
a

array([16, 28, 76, 92, 72, 95, 59, 14, 23, 30, 39, 27, 11, 36, 76])

In [28]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 2,  3,  4,  5,  6, 14], dtype=int64),)

In [29]:
# replace all values > 50 with 0
np.where(a>50,0,a) # np.where(condition,true,false)

array([16, 28,  0,  0,  0,  0,  0, 14, 23, 30, 39, 27, 11, 36,  0])

In [30]:
np.where(a%2 == 0,0,a)

array([ 0,  0,  0,  0,  0, 95, 59,  0, 23,  0, 39, 27, 11,  0,  0])

# np.argmax & np.argmin

The numpy.argmax() function returns indices of the max element of the array in a particular axis and vice-versa for numpy.argmin()

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [31]:
# code
a

array([16, 28, 76, 92, 72, 95, 59, 14, 23, 30, 39, 27, 11, 36, 76])

In [32]:
np.argmax(a)

5

In [33]:
b

array([[23, 30, 65, 65],
       [34, 39, 80, 97],
       [29, 17, 26, 78],
       [34, 12, 59, 99],
       [48, 71,  3, 33],
       [38, 36, 68, 87]])

In [34]:
np.argmax(b,axis=0)

array([4, 4, 1, 3], dtype=int64)

In [35]:
np.argmax(b,axis=1)

array([2, 3, 3, 3, 1, 3], dtype=int64)

In [36]:
# np.argmin
np.argmin(a)

12

In [37]:
# np.argmin
np.argmin(b,axis=0)

array([0, 3, 4, 4], dtype=int64)

In [38]:
# np.argmin
np.argmin(b,axis=1)

array([0, 0, 1, 1, 2, 1], dtype=int64)

# np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [39]:
a

array([16, 28, 76, 92, 72, 95, 59, 14, 23, 30, 39, 27, 11, 36, 76])

In [40]:
np.cumsum(a)

array([ 16,  44, 120, 212, 284, 379, 438, 452, 475, 505, 544, 571, 582,
       618, 694])

In [ ]:
b