# Numpy
## Numpy is a library for the Python programming language, adding support for large, ;ulti-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
##
## Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.
##
## Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.p[=\p[=\
###  also has functions for working in domain of linear algebra, fourier transform, and matrices. 
  

In [2]:
import numpy as np

## We have imported the numpy library as np. Now we can use the functions in the library by using np.function_name.
## Arrays are stored in contiguous memory locations. They are faster than lists.
## Arrays are mutable. We can change the values of the array.
## Arrays are homogeneous. All the elements of the array should be of the same data type.6]
## Arrays are of fixed size. We cannot increase or decrease the size of the array.


In [3]:
# Creating an array
a = np.array([1,2,3,4,5])
print(a) 
print(type(a)) # type of the array
print(a.shape) # shape of the array 
print(a.dtype) # data type of the array
print(a.size) # number of elements in the array
print(a.ndim) # number of dimensions of the array
print(a.itemsize) # size of each element in the array


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
int32
5
1
4


In [4]:
# Addition of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a + b
print(c)

[ 7  9 11 13 15]


In [5]:
# Subtraction of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a - b
print(c)

[-5 -5 -5 -5 -5]


In [6]:
# Multiplication of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a * b
print(c)

[ 6 14 24 36 50]


In [7]:
# Division of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a / b
print(c)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [8]:
# Dot product of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.dot(a,b)
print(c)

130


In [9]:
# Creating a 2D array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# Accessing elements of a 2D array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0,0]) # first element
print(a[0,1]) # second element


1
2


In [11]:
# Slicing of a 2D array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0:2,0:2])  #irst two rows and first two columns

[[1 2]
 [4 5]]


In [12]:
# Creating a 4 x 2 matrix
a = np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [13]:
# 3d Array
c = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [14]:
#dtype

a = np.array([0,2,3],dtype=bool)
print(a)
b = np.array([0,2,3],dtype=complex)
print(b)

[False  True  True]
[0.+0.j 2.+0.j 3.+0.j]


In [15]:
# np.arange
a = np.arange(1,11)
print(a)
b = np.arange(1,11,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [16]:
# with reshape

np.arange(1,11).reshape(2,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
a =np.arange(1,11).reshape(5,2)
print(a)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [18]:
# np.ones and np.zeros
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
b = np.zeros((3,3))
print(b)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
# np.random
a = np.random.random((3,3))

In [21]:
print(a)

[[0.87720509 0.54440494 0.76605566]
 [0.12763732 0.92024257 0.55456342]
 [0.02074897 0.85302765 0.29772343]]


In [22]:
# np.linspace
a = np.linspace(1,10,5) # 5 numbers between 1 and 10
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


In [23]:
# np.eye
a = np.eye(3) # 3 x 3 identity matrix
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# np.full
a = np.full((3,3),5) # 3 x 3 matrix with all elements as 5
print(a)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [25]:
# np.empty
a = np.empty((3,3)) # 3 x 3 matrix with random values
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Numpy Attributes


In [26]:
a1 = np.arange(10) # 1D array
print(a1)
a2 = np.arange(12).reshape(3,4) # 2D array
print(a2)
a3 = np.arange(24).reshape(2,3,4) # 3D array
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [27]:
# ndim
print(a1.ndim) # number of dimensions
print(a2.ndim)
print(a3.ndim)

1
2
3


In [28]:
# shape
print(a1.shape) # number of elements in each dimension
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 3, 4)


In [29]:
# size
print(a1.size) # number of elements in the array
print(a2.size)
print(a3.size)

10
12
24


In [30]:
# itemsize
print(a1.itemsize) # size of each element in the array
print(a2.itemsize)
print(a3.itemsize)

4
4
4


In [31]:
# dtype
print(a1.dtype) # data type of the array
print(a2.dtype)
print(a3.dtype)

int32
int32
int32


# Changing Datatype of Array

In [32]:
# astype
a3.dtype

dtype('int32')

In [33]:
a3 = a3.astype(float)

In [34]:
a3.dtype

dtype('float64')

# Array Operations

In [35]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [36]:
# Scalar operations

# arithmetic operations
print(a1 + 2)
print(a1 - 2)
print(a1 * 2)
print(a1 / 2)


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [37]:
# relational operations
print(a1 > 5)
print(a1 < 5)
print(a1 == 5)
print(a1 != 5)


[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True False False False]
 [False False False False]]
[[False False False False]
 [False  True False False]
 [False False False False]]
[[ True  True  True  True]
 [ True False  True  True]
 [ True  True  True  True]]


In [38]:
# Vector operations

# arithmetic operations
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)
    

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


# Numpy Functions

In [39]:
a1 = np.random.random((3,3))
a1 =np.round(a1*100) # round off the elements of the array 
print(a1)

[[69. 97. 39.]
 [48. 66. 60.]
 [ 8. 26. 35.]]


In [40]:
# max / min / sum / prod
print(a1.max()) # maximum element
print(a1.min()) # minimum element
print(a1.sum()) # sum of all elements
print(a1.prod()) # product of all elements

97.0
8.0
448.0
361204568524800.0


In [41]:
# mean / median / std / var
print(a1.mean()) # mean
print(np.median(a1)) # median
print(a1.std()) # standard deviation
print(a1.var()) # variance

49.77777777777778
48.0
24.979003528642824
623.9506172839506


In [42]:
# For each row
print(a1.max(axis=1)) # maximum element in each row
# 1 -> row

[97. 66. 35.]


In [43]:
# For each column
print(a1.max(axis=0)) # maximum element in each column
# 0 -> column

[69. 97. 60.]


In [44]:
# trigonometric functions
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))


[[-0.11478481  0.37960774  0.96379539]
 [-0.76825466 -0.02655115 -0.30481062]
 [ 0.98935825  0.76255845 -0.42818267]]
[[ 0.99339038 -0.92514754  0.26664293]
 [-0.64014434 -0.99964746 -0.95241298]
 [-0.14550003  0.64691932 -0.90369221]]
[[-0.11554855 -0.4103213   3.61455441]
 [ 1.20012724  0.02656052  0.32004039]
 [-6.79971146  1.17875355  0.47381472]]


In [45]:
# exponential functions
print(np.exp(a1))
print(np.log(a1))
print(np.log10(a1)) # log base 10


[[9.25378173e+29 1.33833472e+42 8.65934004e+16]
 [7.01673591e+20 4.60718663e+28 1.14200739e+26]
 [2.98095799e+03 1.95729609e+11 1.58601345e+15]]
[[4.2341065  4.57471098 3.66356165]
 [3.87120101 4.18965474 4.09434456]
 [2.07944154 3.25809654 3.55534806]]
[[1.83884909 1.98677173 1.59106461]
 [1.68124124 1.81954394 1.77815125]
 [0.90308999 1.41497335 1.54406804]]


In [46]:
# Dot Products
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(3,4)
np.dot(a2,a3.T) # dot product of two arrays a2 and a3 


array([[ 86, 110, 134],
       [302, 390, 478],
       [518, 670, 822]])

In [47]:
# Transpose
a1.T


array([[69., 48.,  8.],
       [97., 66., 26.],
       [39., 60., 35.]])

In [48]:
# Inverse
np.linalg.inv(a1)


array([[-0.02050861,  0.06510801, -0.08876128],
       [ 0.03281378, -0.05750615,  0.06201805],
       [-0.01968827,  0.02783702,  0.00278917]])

In [49]:
# round / floor / ceil
print(np.round(3.14))
print(np.floor(3.14))
print(np.ceil(3.14))

3.0
3.0
4.0


In [50]:
# unique
a1 = np.array([1,2,3,4,5,1,2,3,4,5])
print(np.unique(a1)) # unique elements in the array


[1 2 3 4 5]


# Numpy Indexing and Slicing

In [51]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(24).reshape(2,3,4)

In [53]:
print(a1[0]) # first element
print(a1[-1]) # last element

0
9


In [55]:
print(a3[0,0,0]) # first element

0


In [56]:
# Slicing 
print(a1[0:5]) # first five elements
print(a1[:5]) # first five elements
print(a1[5:]) # elements from index 5
print(a1[::2]) # every second element


[0 1 2 3 4]
[0 1 2 3 4]
[5 6 7 8 9]
[0 2 4 6 8]


In [57]:
# Slicing 2D array
print(a2[0,0]) # first element
print(a2[0,0:2]) # first row and first two columns


0
[0 1]


In [58]:
# Slicing 3D array
print(a3[0,0,0]) # first element
print(a3[0,0,0:2]) # first row and first two columns
print(a3[0,0:2,0:2]) # first two rows and first two columns


0
[0 1]
[[0 1]
 [4 5]]


In [60]:
# Printing corner elements of a 2D array
print(a2[0:1,0:2]) # first two rows and first two columns


[[0 1]]
