# Numpy
## Numpy is a library for the Python programming language, adding support for large, ;ulti-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
##
## Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.
##
## Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.p[=\p[=\
###  also has functions for working in domain of linear algebra, fourier transform, and matrices. 
  

In [2]:
import numpy as np

## We have imported the numpy library as np. Now we can use the functions in the library by using np.function_name.
## Arrays are stored in contiguous memory locations. They are faster than lists.
## Arrays are mutable. We can change the values of the array.
## Arrays are homogeneous. All the elements of the array should be of the same data type.6]
## Arrays are of fixed size. We cannot increase or decrease the size of the array.


In [3]:
# Creating an array
a = np.array([1,2,3,4,5])
print(a) 
print(type(a)) # type of the array
print(a.shape) # shape of the array 
print(a.dtype) # data type of the array
print(a.size) # number of elements in the array
print(a.ndim) # number of dimensions of the array
print(a.itemsize) # size of each element in the array


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
int32
5
1
4


In [4]:
# Addition of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a + b
print(c)

[ 7  9 11 13 15]


In [5]:
# Subtraction of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a - b
print(c)

[-5 -5 -5 -5 -5]


In [6]:
# Multiplication of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a * b
print(c)

[ 6 14 24 36 50]


In [7]:
# Division of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a / b
print(c)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [8]:
# Dot product of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.dot(a,b)
print(c)

130


In [9]:
# Creating a 2D array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# Accessing elements of a 2D array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0,0]) # first element
print(a[0,1]) # second element


1
2


In [17]:
# Slicing of a 2D array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0:2,0:2])  #irst two rows and first two columns

[[1 2]
 [4 5]]


In [18]:
# Creating a 4 x 2 matrix
a = np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
# 3d Array
c = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [20]:
#dtype

a = np.array([0,2,3],dtype=bool)
print(a)
b = np.array([0,2,3],dtype=complex)
print(b)

[False  True  True]
[0.+0.j 2.+0.j 3.+0.j]


In [21]:
# np.arange
a = np.arange(1,11)
print(a)
b = np.arange(1,11,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [22]:
# with reshape

np.arange(1,11).reshape(2,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
a =np.arange(1,11).reshape(5,2)
print(a)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [27]:
# np.ones and np.zeros
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
b = np.zeros((3,3))
print(b)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
# np.random
a = np.random.random((3,3))

In [30]:
print(a)

[[0.32618011 0.16345066 0.94933387]
 [0.2028032  0.36179844 0.52093013]
 [0.20867362 0.53295478 0.21601279]]


In [31]:
# np.linspace
a = np.linspace(1,10,5) # 5 numbers between 1 and 10
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


In [32]:
# np.eye
a = np.eye(3) # 3 x 3 identity matrix
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
# np.full
a = np.full((3,3),5) # 3 x 3 matrix with all elements as 5
print(a)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [34]:
# np.empty
a = np.empty((3,3)) # 3 x 3 matrix with random values
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Numpy Attributes


In [35]:
a1 = np.arange(10) # 1D array
print(a1)
a2 = np.arange(12).reshape(3,4) # 2D array
print(a2)
a3 = np.arange(24).reshape(2,3,4) # 3D array
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [36]:
# ndim
print(a1.ndim) # number of dimensions
print(a2.ndim)
print(a3.ndim)

1
2
3


In [37]:
# shape
print(a1.shape) # number of elements in each dimension
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 3, 4)


In [38]:
# size
print(a1.size) # number of elements in the array
print(a2.size)
print(a3.size)

10
12
24


In [39]:
# itemsize
print(a1.itemsize) # size of each element in the array
print(a2.itemsize)
print(a3.itemsize)

4
4
4


In [40]:
# dtype
print(a1.dtype) # data type of the array
print(a2.dtype)
print(a3.dtype)

int32
int32
int32


# Changing Datatype of Array

In [41]:
# astype
a3.dtype

dtype('int32')

In [42]:
a3 = a3.astype(float)

In [43]:
a3.dtype

dtype('float64')

# Array Operations

In [44]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [45]:
# Scalar operations

# arithmetic operations
print(a1 + 2)
print(a1 - 2)
print(a1 * 2)
print(a1 / 2)


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [46]:
# relational operations
print(a1 > 5)
print(a1 < 5)
print(a1 == 5)
print(a1 != 5)


[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True False False False]
 [False False False False]]
[[False False False False]
 [False  True False False]
 [False False False False]]
[[ True  True  True  True]
 [ True False  True  True]
 [ True  True  True  True]]


In [47]:
# Vector operations

# arithmetic operations
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)
    

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


# Numpy Functions

In [49]:
a1 = np.random.random((3,3))
a1 =np.round(a1*100) # round off the elements of the array 
print(a1)

[[40. 57.  0.]
 [42. 11. 50.]
 [68. 10. 45.]]


In [50]:
# max / min / sum / prod
print(a1.max()) # maximum element
print(a1.min()) # minimum element
print(a1.sum()) # sum of all elements
print(a1.prod()) # product of all elements

68.0
0.0
323.0
0.0


In [51]:
# mean / median / std / var
print(a1.mean()) # mean
print(np.median(a1)) # median
print(a1.std()) # standard deviation
print(a1.var()) # variance

35.888888888888886
42.0
22.087927544472716
487.8765432098765


In [52]:
# For each row
print(a1.max(axis=1)) # maximum element in each row
# 1 -> row

[57. 50. 68.]


In [53]:
# For each column
print(a1.max(axis=0)) # maximum element in each column
# 0 -> column

[68. 57. 50.]


In [54]:
# trigonometric functions
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))


[[ 0.74511316  0.43616476  0.        ]
 [-0.91652155 -0.99999021 -0.26237485]
 [-0.89792768 -0.54402111  0.85090352]]
[[-0.66693806  0.89986683  1.        ]
 [-0.39998531  0.0044257   0.96496603]
 [ 0.44014302 -0.83907153  0.52532199]]
[[  -1.11721493    0.48469923    0.        ]
 [   2.29138799 -225.95084645   -0.27190061]
 [  -2.0400816     0.64836083    1.61977519]]


In [55]:
# exponential functions
print(np.exp(a1))
print(np.log(a1))
print(np.log10(a1)) # log base 10


[[2.35385267e+17 5.68572000e+24 1.00000000e+00]
 [1.73927494e+18 5.98741417e+04 5.18470553e+21]
 [3.40427605e+29 2.20264658e+04 3.49342711e+19]]
[[3.68887945 4.04305127       -inf]
 [3.73766962 2.39789527 3.91202301]
 [4.21950771 2.30258509 3.80666249]]
[[1.60205999 1.75587486       -inf]
 [1.62324929 1.04139269 1.69897   ]
 [1.83250891 1.         1.65321251]]


C:\Users\Administrator\AppData\Local\Temp\2\ipykernel_6836\2372518407.py:3: RuntimeWarning: divide by zero encountered in log
  print(np.log(a1))
C:\Users\Administrator\AppData\Local\Temp\2\ipykernel_6836\2372518407.py:4: RuntimeWarning: divide by zero encountered in log10
  print(np.log10(a1))


In [64]:
# Dot Products
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(3,4)
np.dot(a2,a3.T) # dot product of two arrays a2 and a3 


array([[ 86, 110, 134],
       [302, 390, 478],
       [518, 670, 822]])

In [57]:
# Transpose
a1.T


array([[40., 42., 68.],
       [57., 11., 10.],
       [ 0., 50., 45.]])

In [58]:
# Inverse
np.linalg.inv(a1)


array([[-5.82275533e-05, -2.98707348e-02,  3.31897054e-02],
       [ 1.75847211e-02,  2.09619192e-02, -2.32910213e-02],
       [-3.81972750e-03,  4.04797950e-02, -2.27553278e-02]])

In [59]:
# round / floor / ceil
print(np.round(3.14))
print(np.floor(3.14))
print(np.ceil(3.14))

3.0
3.0
4.0


In [60]:
# unique
a1 = np.array([1,2,3,4,5,1,2,3,4,5])
print(np.unique(a1)) # unique elements in the array


[1 2 3 4 5]


# Numpy Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(24).reshape(2,3,4)