# Numpy
## Numpy is a library for the Python programming language, adding support for large, ;ulti-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
##
## Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.
##
## Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.p[=\p[=\
###  also has functions for working in domain of linear algebra, fourier transform, and matrices. 
  

In [1]:
import numpy as np

## We have imported the numpy library as np. Now we can use the functions in the library by using np.function_name.
## Arrays are stored in contiguous memory locations. They are faster than lists.
## Arrays are mutable. We can change the values of the array.
## Arrays are homogeneous. All the elements of the array should be of the same data type.6]
## Arrays are of fixed size. We cannot increase or decrease the size of the array.


In [2]:
# Creating an array
a = np.array([1,2,3,4,5])
print(a) 
print(type(a)) # type of the array
print(a.shape) # shape of the array 
print(a.dtype) # data type of the array
print(a.size) # number of elements in the array
print(a.ndim) # number of dimensions of the array
print(a.itemsize) # size of each element in the array


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
int32
5
1
4


In [3]:
# Addition of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a + b
print(c)

[ 7  9 11 13 15]


In [4]:
# Subtraction of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a - b
print(c)

[-5 -5 -5 -5 -5]


In [5]:
# Multiplication of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a * b
print(c)

[ 6 14 24 36 50]


In [6]:
# Division of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a / b
print(c)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [7]:
# Dot product of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.dot(a,b)
print(c)

130


In [8]:
# Creating a 2D array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# Accessing elements of a 2D array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0,0]) # first element
print(a[0,1]) # second element


1
2


In [10]:
# Slicing of a 2D array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0:2,0:2])  #irst two rows and first two columns

[[1 2]
 [4 5]]


In [11]:
# Creating a 4 x 2 matrix
a = np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [12]:
# 3d Array
c = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [13]:
#dtype

a = np.array([0,2,3],dtype=bool)
print(a)
b = np.array([0,2,3],dtype=complex)
print(b)

[False  True  True]
[0.+0.j 2.+0.j 3.+0.j]


In [14]:
# np.arange
a = np.arange(1,11)
print(a)
b = np.arange(1,11,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [15]:
# with reshape

np.arange(1,11).reshape(2,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
a =np.arange(1,11).reshape(5,2)
print(a)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [17]:
# np.ones and np.zeros
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
b = np.zeros((3,3))
print(b)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# np.random
a = np.random.random((3,3))

In [20]:
print(a)

[[0.50876825 0.20187444 0.93749723]
 [0.16846637 0.94957065 0.06668859]
 [0.73956402 0.95543318 0.28135507]]


In [21]:
# np.linspace
a = np.linspace(1,10,5) # 5 numbers between 1 and 10
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


In [22]:
# np.eye
a = np.eye(3) # 3 x 3 identity matrix
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
# np.full
a = np.full((3,3),5) # 3 x 3 matrix with all elements as 5
print(a)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [24]:
# np.empty
a = np.empty((3,3)) # 3 x 3 matrix with random values
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Numpy Attributes


In [25]:
a1 = np.arange(10) # 1D array
print(a1)
a2 = np.arange(12).reshape(3,4) # 2D array
print(a2)
a3 = np.arange(24).reshape(2,3,4) # 3D array
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [26]:
# ndim
print(a1.ndim) # number of dimensions
print(a2.ndim)
print(a3.ndim)

1
2
3


In [27]:
# shape
print(a1.shape) # number of elements in each dimension
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 3, 4)


In [28]:
# size
print(a1.size) # number of elements in the array
print(a2.size)
print(a3.size)

10
12
24


In [29]:
# itemsize
print(a1.itemsize) # size of each element in the array
print(a2.itemsize)
print(a3.itemsize)

4
4
4


In [30]:
# dtype
print(a1.dtype) # data type of the array
print(a2.dtype)
print(a3.dtype)

int32
int32
int32


# Changing Datatype of Array

In [31]:
# astype
a3.dtype

dtype('int32')

In [32]:
a3 = a3.astype(float)

In [33]:
a3.dtype

dtype('float64')

# Array Operations

In [34]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [35]:
# Scalar operations

# arithmetic operations
print(a1 + 2)
print(a1 - 2)
print(a1 * 2)
print(a1 / 2)


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [36]:
# relational operations
print(a1 > 5)
print(a1 < 5)
print(a1 == 5)
print(a1 != 5)


[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True False False False]
 [False False False False]]
[[False False False False]
 [False  True False False]
 [False False False False]]
[[ True  True  True  True]
 [ True False  True  True]
 [ True  True  True  True]]


In [37]:
# Vector operations

# arithmetic operations
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)
    

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


# Numpy Functions

In [38]:
a1 = np.random.random((3,3))
a1 =np.round(a1*100) # round off the elements of the array 
print(a1)

[[84. 59. 34.]
 [84. 67. 58.]
 [79. 67. 88.]]


In [39]:
# max / min / sum / prod
print(a1.max()) # maximum element
print(a1.min()) # minimum element
print(a1.sum()) # sum of all elements
print(a1.prod()) # product of all elements

88.0
34.0
620.0
2.5619866548401664e+16


In [40]:
# mean / median / std / var
print(a1.mean()) # mean
print(np.median(a1)) # median
print(a1.std()) # standard deviation
print(a1.var()) # variance

68.88888888888889
67.0
16.210041088743896
262.7654320987654


In [41]:
# For each row
print(a1.max(axis=1)) # maximum element in each row
# 1 -> row

[84. 84. 88.]


In [42]:
# For each column
print(a1.max(axis=0)) # maximum element in each column
# 0 -> column

[84. 67. 88.]


In [43]:
# trigonometric functions
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))


[[ 0.73319032  0.63673801  0.52908269]
 [ 0.73319032 -0.85551998  0.99287265]
 [-0.44411267 -0.85551998  0.0353983 ]]
[[-0.6800235  -0.77108022 -0.84857027]
 [-0.6800235  -0.5177698   0.11918014]
 [-0.89597095 -0.5177698   0.99937328]]
[[-1.07818381 -0.82577401 -0.62349896]
 [-1.07818381  1.65231726  8.33085685]
 [ 0.49567753  1.65231726  0.0354205 ]]


In [44]:
# exponential functions
print(np.exp(a1))
print(np.log(a1))
print(np.log10(a1)) # log base 10


[[3.02507732e+36 4.20121040e+25 5.83461743e+14]
 [3.02507732e+36 1.25236317e+29 1.54553894e+25]
 [2.03828107e+34 1.25236317e+29 1.65163625e+38]]
[[4.4308168  4.07753744 3.52636052]
 [4.4308168  4.20469262 4.06044301]
 [4.36944785 4.20469262 4.47733681]]
[[1.92427929 1.77085201 1.53147892]
 [1.92427929 1.8260748  1.76342799]
 [1.89762709 1.8260748  1.94448267]]


In [45]:
# Dot Products
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(3,4)
np.dot(a2,a3.T) # dot product of two arrays a2 and a3 


array([[ 86, 110, 134],
       [302, 390, 478],
       [518, 670, 822]])

In [46]:
# Transpose
a1.T


array([[84., 84., 79.],
       [59., 67., 67.],
       [34., 58., 88.]])

In [47]:
# Inverse
np.linalg.inv(a1)


array([[ 0.13919668, -0.20180055,  0.07922438],
       [-0.19459834,  0.32590028, -0.13961219],
       [ 0.02319945, -0.06696676,  0.0465374 ]])

In [48]:
# round / floor / ceil
print(np.round(3.14))
print(np.floor(3.14))
print(np.ceil(3.14))

3.0
3.0
4.0


In [49]:
# unique
a1 = np.array([1,2,3,4,5,1,2,3,4,5])
print(np.unique(a1)) # unique elements in the array


[1 2 3 4 5]


# Numpy Indexing and Slicing

In [50]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(24).reshape(2,3,4)

In [51]:
print(a1[0]) # first element
print(a1[-1]) # last element

0
9


In [52]:
print(a3[0,0,0]) # first element

0


In [53]:
# Slicing 
print(a1[0:5]) # first five elements
print(a1[:5]) # first five elements
print(a1[5:]) # elements from index 5
print(a1[::2]) # every second element


[0 1 2 3 4]
[0 1 2 3 4]
[5 6 7 8 9]
[0 2 4 6 8]


In [54]:
# Slicing 2D array
print(a2[0,0]) # first element
print(a2[0,0:2]) # first row and first two columns


0
[0 1]


In [55]:
# Slicing 3D array
print(a3[0,0,0]) # first element
print(a3[0,0,0:2]) # first row and first two columns
print(a3[0,0:2,0:2]) # first two rows and first two columns


0
[0 1]
[[0 1]
 [4 5]]


In [56]:
# Printing corner elements of a 2D array
print(a2[0:1,0:2]) # first two rows and first two columns


[[0 1]]


# Iterating over Arrays

In [57]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [60]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [61]:
for i in a2.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [62]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [63]:
for i in np.nditer(a2,order='F'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [64]:
for i in np.nditer(a2,order='C'):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [65]:
for i in np.nditer(a2,flags=['external_loop']): # external loop 
     print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
