# Numpy
## Numpy is a library for the Python programming language, adding support for large, ;ulti-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
##
## Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.
##
## Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.p[=\p[=\
###  also has functions for working in domain of linear algebra, fourier transform, and matrices. 
  

In [68]:
import numpy as np

## We have imported the numpy library as np. Now we can use the functions in the library by using np.function_name.
## Arrays are stored in contiguous memory locations. They are faster than lists.
## Arrays are mutable. We can change the values of the array.
## Arrays are homogeneous. All the elements of the array should be of the same data type.6]
## Arrays are of fixed size. We cannot increase or decrease the size of the array.


In [69]:
# Creating an array
a = np.array([1,2,3,4,5])
print(a) 
print(type(a)) # type of the array
print(a.shape) # shape of the array 
print(a.dtype) # data type of the array
print(a.size) # number of elements in the array
print(a.ndim) # number of dimensions of the array
print(a.itemsize) # size of each element in the array


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
int32
5
1
4


In [70]:
# Addition of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a + b
print(c)

[ 7  9 11 13 15]


In [71]:
# Subtraction of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a - b
print(c)

[-5 -5 -5 -5 -5]


In [72]:
# Multiplication of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a * b
print(c)

[ 6 14 24 36 50]


In [73]:
# Division of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a / b
print(c)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [74]:
# Dot product of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.dot(a,b)
print(c)

130


In [75]:
# Creating a 2D array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
# Accessing elements of a 2D array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0,0]) # first element
print(a[0,1]) # second element


1
2


In [77]:
# Slicing of a 2D array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0:2,0:2])  #irst two rows and first two columns

[[1 2]
 [4 5]]


In [78]:
# Creating a 4 x 2 matrix
a = np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [79]:
# 3d Array
c = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [80]:
#dtype

a = np.array([0,2,3],dtype=bool)
print(a)
b = np.array([0,2,3],dtype=complex)
print(b)

[False  True  True]
[0.+0.j 2.+0.j 3.+0.j]


In [81]:
# np.arange
a = np.arange(1,11)
print(a)
b = np.arange(1,11,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [82]:
# with reshape

np.arange(1,11).reshape(2,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [83]:
a =np.arange(1,11).reshape(5,2)
print(a)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [84]:
# np.ones and np.zeros
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [85]:
b = np.zeros((3,3))
print(b)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [86]:
# np.random
a = np.random.random((3,3))

In [87]:
print(a)

[[0.6728589  0.09794667 0.2942666 ]
 [0.24164844 0.85593302 0.09477387]
 [0.51547219 0.37220659 0.87810424]]


In [88]:
# np.linspace
a = np.linspace(1,10,5) # 5 numbers between 1 and 10
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


In [89]:
# np.eye
a = np.eye(3) # 3 x 3 identity matrix
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [90]:
# np.full
a = np.full((3,3),5) # 3 x 3 matrix with all elements as 5
print(a)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [91]:
# np.empty
a = np.empty((3,3)) # 3 x 3 matrix with random values
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Numpy Attributes


In [92]:
a1 = np.arange(10) # 1D array
print(a1)
a2 = np.arange(12).reshape(3,4) # 2D array
print(a2)
a3 = np.arange(24).reshape(2,3,4) # 3D array
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [93]:
# ndim
print(a1.ndim) # number of dimensions
print(a2.ndim)
print(a3.ndim)

1
2
3


In [94]:
# shape
print(a1.shape) # number of elements in each dimension
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 3, 4)


In [95]:
# size
print(a1.size) # number of elements in the array
print(a2.size)
print(a3.size)

10
12
24


In [96]:
# itemsize
print(a1.itemsize) # size of each element in the array
print(a2.itemsize)
print(a3.itemsize)

4
4
4


In [97]:
# dtype
print(a1.dtype) # data type of the array
print(a2.dtype)
print(a3.dtype)

int32
int32
int32


# Changing Datatype of Array

In [98]:
# astype
a3.dtype

dtype('int32')

In [99]:
a3 = a3.astype(float)

In [100]:
a3.dtype

dtype('float64')

# Array Operations

In [101]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [102]:
# Scalar operations

# arithmetic operations
print(a1 + 2)
print(a1 - 2)
print(a1 * 2)
print(a1 / 2)


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [103]:
# relational operations
print(a1 > 5)
print(a1 < 5)
print(a1 == 5)
print(a1 != 5)


[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True False False False]
 [False False False False]]
[[False False False False]
 [False  True False False]
 [False False False False]]
[[ True  True  True  True]
 [ True False  True  True]
 [ True  True  True  True]]


In [104]:
# Vector operations

# arithmetic operations
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)
    

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


# Numpy Functions

In [105]:
a1 = np.random.random((3,3))
a1 =np.round(a1*100) # round off the elements of the array 
print(a1)

[[65. 24. 58.]
 [97. 52.  7.]
 [44. 15. 15.]]


In [106]:
# max / min / sum / prod
print(a1.max()) # maximum element
print(a1.min()) # minimum element
print(a1.sum()) # sum of all elements
print(a1.prod()) # product of all elements

97.0
7.0
377.0
31627211616000.0


In [107]:
# mean / median / std / var
print(a1.mean()) # mean
print(np.median(a1)) # median
print(a1.std()) # standard deviation
print(a1.var()) # variance

41.888888888888886
44.0
27.730626648544884
768.9876543209878


In [108]:
# For each row
print(a1.max(axis=1)) # maximum element in each row
# 1 -> row

[65. 97. 44.]


In [109]:
# For each column
print(a1.max(axis=0)) # maximum element in each column
# 0 -> column

[97. 52. 58.]


In [110]:
# trigonometric functions
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))


[[ 0.82682868 -0.90557836  0.99287265]
 [ 0.37960774  0.98662759  0.6569866 ]
 [ 0.01770193  0.65028784  0.65028784]]
[[-0.56245385  0.42417901  0.11918014]
 [-0.92514754 -0.16299078  0.75390225]
 [ 0.99984331 -0.75968791 -0.75968791]]
[[-1.47003826 -2.1348967   8.33085685]
 [-0.4103213  -6.05327238  0.87144798]
 [ 0.0177047  -0.8559934  -0.8559934 ]]


In [111]:
# exponential functions
print(np.exp(a1))
print(np.log(a1))
print(np.log10(a1)) # log base 10


[[1.69488924e+28 2.64891221e+10 1.54553894e+25]
 [1.33833472e+42 3.83100800e+22 1.09663316e+03]
 [1.28516001e+19 3.26901737e+06 3.26901737e+06]]
[[4.17438727 3.17805383 4.06044301]
 [4.57471098 3.95124372 1.94591015]
 [3.78418963 2.7080502  2.7080502 ]]
[[1.81291336 1.38021124 1.76342799]
 [1.98677173 1.71600334 0.84509804]
 [1.64345268 1.17609126 1.17609126]]


In [112]:
# Dot Products
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(3,4)
np.dot(a2,a3.T) # dot product of two arrays a2 and a3 


array([[ 86, 110, 134],
       [302, 390, 478],
       [518, 670, 822]])

In [113]:
# Transpose
a1.T


array([[65., 97., 44.],
       [24., 52., 15.],
       [58.,  7., 15.]])

In [114]:
# Inverse
np.linalg.inv(a1)


array([[-0.02111553, -0.01595395,  0.08909188],
       [ 0.03588075,  0.04933212, -0.16176057],
       [ 0.02605812, -0.00253386, -0.03290894]])

In [115]:
# round / floor / ceil
print(np.round(3.14))
print(np.floor(3.14))
print(np.ceil(3.14))

3.0
3.0
4.0


In [116]:
# unique
a1 = np.array([1,2,3,4,5,1,2,3,4,5])
print(np.unique(a1)) # unique elements in the array


[1 2 3 4 5]


# Numpy Indexing and Slicing

In [117]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(24).reshape(2,3,4)

In [118]:
print(a1[0]) # first element
print(a1[-1]) # last element

0
9


In [119]:
print(a3[0,0,0]) # first element

0


In [120]:
# Slicing 
print(a1[0:5]) # first five elements
print(a1[:5]) # first five elements
print(a1[5:]) # elements from index 5
print(a1[::2]) # every second element


[0 1 2 3 4]
[0 1 2 3 4]
[5 6 7 8 9]
[0 2 4 6 8]


In [121]:
# Slicing 2D array
print(a2[0,0]) # first element
print(a2[0,0:2]) # first row and first two columns


0
[0 1]


In [122]:
# Slicing 3D array
print(a3[0,0,0]) # first element
print(a3[0,0,0:2]) # first row and first two columns
print(a3[0,0:2,0:2]) # first two rows and first two columns


0
[0 1]
[[0 1]
 [4 5]]


In [123]:
# Printing corner elements of a 2D array
print(a2[0:1,0:2]) # first two rows and first two columns


[[0 1]]


# Iterating over Arrays

In [124]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [127]:
for i in a2: 
    print(i) # row by row

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [128]:
for i in a2.flat: # flatten the array
    print(i)     # element by element

0
1
2
3
4
5
6
7
8
9
10
11


In [129]:
for i in np.nditer(a2): # default order
    print(i)  # element by element

0
1
2
3
4
5
6
7
8
9
10
11


In [130]:
for i in np.nditer(a2,order='F'): # Fortran order
    print(i) #  column by column

0
4
8
1
5
9
2
6
10
3
7
11


In [131]:
for i in np.nditer(a2,order='C'): # C order
    print(i) # row by row

0
1
2
3
4
5
6
7
8
9
10
11


In [132]:
for i in np.nditer(a2,flags=['external_loop']): # external loop 
     print(i) # row by row

[ 0  1  2  3  4  5  6  7  8  9 10 11]


# Reshaping Arrays


In [133]:
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [135]:
a2.T # transpose the array 

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [136]:
a2.reshape(4,3) # reshape the array to 4 x 3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [137]:
# ravel

a2.ravel() # flatten the array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stack Arrays

In [138]:
# Horizontal Stack
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
np.hstack((a1,a2))


array([1, 2, 3, 4, 5, 6])

In [139]:
# Vertical Stack
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
np.vstack((a1,a2))


array([[1, 2, 3],
       [4, 5, 6]])

# Splitting Arrays

In [140]:
a1 = np.arange(10)
np.split(a1,2) # split the array into two equal parts


[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [141]:
a2 = np.arange(12).reshape(3,4)
np.vsplit(a2,3) # split the array into three equal parts

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [142]:
np.hsplit(a2,2) # split the array into two equal parts

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]